import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import xarray as xr


def sensor_data(df: pd.DataFrame, df3: pd.DataFrame) -> pd.DataFrame:
    """ This function will clean the sensor dataframe to retain just the PM2.5 values and set the date as the index.
    The dataframe generated by this function will be merged with other dataframes to create a dataframe containing
    all sensor data for the same time period.

    :param df: Dataframe generated by the purple air sensor data stored in a feather file
    :param df3: Dataframe generated by the UIUC sensor data stored in a feather file
    :return: Cleaned dataframe to be merged with other sensor data

    >>> a = pd.read_feather('export_Urbana_feather', columns=None, use_threads=True)
    >>> b = pd.read_feather('export_UIUC_feather', columns=None, use_threads=True)
    >>> test_df = sensor_data(a, b)
    >>> test_df.size
    8528
    """
    df3 = df3.drop(['index'], axis=1)
    df3.rename(columns={'reading_datestamp': 'new_date'}, inplace=True)
    df3.head(5)
    df3['new_date'] = pd.to_datetime(df3['new_date'])
    df3.set_index('new_date', inplace=True)

    df['new_date'] = pd.to_datetime(df['new_date'])
    df = df[['new_date', 'PM2.5 (CF=1) ug/m3']]
    df.set_index('new_date', inplace=True)
    df = df[df.index.isin(df3.index)]
    return df


def wind_filter(date: str, lat: str, lon: str) -> pd.DataFrame:
    """ This function will filter the windspeed data for a particular location and a particular data from NASA's MERRA-2
    geographical data. The file should be downloaded in the directory before calling this function.

    :param date: Date for which windspeed data is required
    :param lat: Latitude of location for which windspeed data is required
    :param lon: Longitude of location for which windspeed data is required
    :return: Dataframe with windspeed data for 24 hours of a particular day and location

    >>> x = wind_filter("20200930", "40.0", "-87.5")
    >>> x.size
    24
    """
    path = "MERRA2_401.inst1_2d_lfo_Nx." + date + ".nc4"
    ds = xr.open_dataset(path)
    location_ds = ds.loc[dict(lat=lat, lon=lon)]
    location_df = location_ds.to_dataframe()
    wind_speed = location_df.reset_index()
    wind_speed['time'] = wind_speed['time'].dt.time
    wind_speed.rename(columns={'time': 'new_date'}, inplace=True)
    wind_speed = wind_speed[['new_date', 'SPEEDLML']]
    wind_speed.set_index("new_date", inplace=True)
    return wind_speed

